### ISSUE TITLE
editorRef maybe null

### ISSUE THREAD

**Issue by Cat1007** [imguolao/monaco-vue#11]
https://github.com/imguolao/monaco-vue/blob/60528daef6131e749ff1a6f16e2f8578ddcaa512/packages/editor/src/components/Editor.ts#L118

if toggle unmounted hook before editorRef inited, this line of code will throw an error
Error: TypeError: Cannot read properties of null (reading 'getModel')

**Comment by imguolao** [comment]
Got it, will be fixed in the next version.

**Comment by imguolao** [comment]
fixed in version@1.1.2
