### ISSUE TITLE
[feat] support diff editor

### ISSUE THREAD

**Issue by Cat1007** [imguolao/monaco-vue#15]
the useMonaco hook can be reuse
use https://microsoft.github.io/monaco-editor/docs.html#functions/editor.createDiffEditor.html to create diffEditor

**Comment by imguolao** [comment]
pr welcome

**Comment by Cat1007** [comment]
nice 🎉🎉🎉🎉

**Comment by imguolao** [comment]
There is still have a lot of work to be done.

- [ ] update the diff editor's description in the README.md
- [ ] test case of vue2.6
- [ ] test case of vue2.7
- [ ] npm publish
- [ ] update website
