### ISSUE TITLE
Not working with 'warn' messages and some configurations

### ISSUE THREAD

**Issue by harin1124** [imguolao/monaco-vue#19]
`[Vue warn]: Failed to resolve component: vue-monaco-editor
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement. 
  at <App>`

When I refer to and implement 'https://github.com/imguolao/monaco-vue#usage' ', the following message pops up.

And 'vue-monaco-editor' is not displayed on the screen.

But if you refer to 'https://github.com/imguolao/monaco-vue#hooks ' here, it works. I want to get rid of the 'warn' message, and I want to make it work as it says here at https://github.com/imguolao/monaco-vue#hooks' .

```json
/* my package.json */
{
  "name": "vue",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "local": "vue-cli-service serve --mode localhost --port 8080",
  },
  "dependencies": {
    "core-js": "^3.8.3",
    "vue": "^3.2.13",
    "monaco-editor": "0.41.0",
    "@guolao/vue-monaco-editor": "1.1.4"
  },
  "devDependencies": {
    "@babel/core": "^7.12.16",
    "@babel/eslint-parser": "^7.12.16",
    "@vue/cli-plugin-babel": "~5.0.0",
    "@vue/cli-plugin-eslint": "~5.0.0",
    "@vue/cli-service": "~5.0.0",
    "eslint": "^7.32.0",
    "eslint-plugin-vue": "^8.0.3"
  },
  "eslintConfig": {
    "root": true,
    "env": {
      "node": true
    },
    "extends": [
      "plugin:vue/vue3-essential",
      "eslint:recommended"
    ],
    "parserOptions": {
      "parser": "@babel/eslint-parser"
    },
    "rules": {}
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not dead",
    "not ie 11"
  ]
}
```

**Comment by imguolao** [comment]
Maybe you don't register the component?

Can look at this [example](https://github.com/imguolao/monaco-vue/blob/4de436f7f349a08132568738df2a28f4bf41c1fd/packages/vue-test-2.7.14/src/main.ts#L2-L5).

**Comment by harin1124** [comment]
thanks!!! I hope you can check that out at readme.md .

**Comment by imguolao** [comment]
> thanks!!! I hope you can check that out at readme.md .谢谢！！！我希望您可以在 readme.md 中查看这一点。

Good, i will add instructions on readme.
