### ISSUE TITLE
0.41.0 The input prompt is not displayed.

### ISSUE THREAD

**Issue by duolabmeng6** [imguolao/monaco-vue#27]
I found that the code prompt of version 36 is normal. If you upgrade to 41, the code prompt will not exist.. Excuse me, can it be repaired?
```
app.use(VueMonacoEditorPlugin, {
  paths: {
    // The default CDN config
    vs: 'https://cdn.jsdelivr.net/npm/monaco-editor@0.36.0/min/vs'
  },
})
```
<img width="401" alt="image" src="https://github.com/imguolao/monaco-vue/assets/59047063/cac6af84-0be4-4a81-a5c7-2a13cddf707d">

**Comment by imguolao** [comment]
No problem found, work normal.
Try 0.38.0？

**Comment by duolabmeng6** [comment]
This is my project.https://github.com/duolabmeng6/GoEasyDesigner 
Online preview address https://go-easy-designer.vercel.app/  
Modify the document  `GoEasyDesigner/frontend/src/main.js`  Set to 41 There is a problem.
Your project has helped me a lot.
I hope the teacher can help me take a look.
```
        vs: 'https://cdn.jsdelivr.net/npm/monaco-editor@0.41.0/min/vs'
```
<img width="445" alt="image" src="https://github.com/imguolao/monaco-vue/assets/59047063/c8c78629-2947-4895-84c3-9f93fc5074fb">

38 is normal.
<img width="633" alt="image" src="https://github.com/imguolao/monaco-vue/assets/59047063/06a655bb-262e-4d4f-be1c-1b28b48ee14a">

**Comment by duolabmeng6** [comment]
These two versions are not good.
```
    "@guolao/vue-monaco-editor": "^1.2.0",
    "monaco-editor": "^0.41.0",
```


There is no problem with these two versions.
```
    "@guolao/vue-monaco-editor": "1.2.0",
    "monaco-editor": "0.40.0",
```

**Comment by imguolao** [comment]
Yep, I found problem too, the recommended version will be rolled back to version 0.38, the default version is still 0.33.

Monaco-editor 0.40 and above may has some breaking changes that the cause of `monaco-loader` can not loading monaco-editor completelly, `loader` to be updated.

**Comment by duolabmeng6** [comment]
Thank You
