### ISSUE TITLE
有的时候会渲染两个panel不知道为啥

### ISSUE THREAD

**Issue by qq1037305420** [imguolao/monaco-vue#3]
![image](https://user-images.githubusercontent.com/28857867/173810958-270dd6f1-f7e3-4b07-af8f-1f3414312782.png)

**Comment by imguolao** [comment]
有复现代码或者步骤么？

我在 vite 下 dev 和 build 好像都没有这个问题，也有可能是我没注意到 🤣

**Comment by qq1037305420** [comment]
偶发的，就看有没有人遇到过。有可能是父级刚刚渲染的时候高度没有，还是怎么样

**Comment by qq1037305420** [comment]
好像发现问题了 如果value传入的是一个undefined或者一个‘’
我这个就会渲染两个panel，我是用的tsx 不知道是不是这个导致的
我说弄个codesandbox搞了半个多小时环境没弄好。

**Comment by imguolao** [comment]
你可以 clone 这个仓库，playground 里面有个例子，你试试能不能复现？

```sh
git clone https://github.com/imguolao/monaco-vue.git

cd monaco-vue

pnpm install
pnpm dev
```

**Comment by imguolao** [comment]
你也可以用复现代码新建一个 github 仓库，发链接给我也行的。

**Comment by imguolao** [comment]
#4
