### ISSUE TITLE
Monaco initialization error: no such file or directory, open 'https:/cdn.jsdelivr.net/npm/monaco-editor@0.43.0/min/vs/editor/editor.main.js'

### ISSUE THREAD

**Issue by mx94** [imguolao/monaco-vue#36]
![image](https://github.com/imguolao/monaco-vue/assets/20527751/cde490b5-90b9-4397-947e-53d8caee45e0)

**Comment by mx94** [comment]
![image](https://github.com/imguolao/monaco-vue/assets/20527751/428c7bcf-37e1-470b-b628-846ed305c4b2)

**Comment by mx94** [comment]
在electron中使用vite构建，CDN引入后报找不到路径，https:/ 为啥会少了个斜杠 :(

**Comment by imguolao** [comment]
Oh, sry!

This is a known issue, but I forgot to put it in the documentation.

Look at [here](https://github.com/suren-atoyan/monaco-react#for-electron-users).

**Comment by mx94** [comment]
thank you!

`
import { createApp } from 'vue'
import { install as VueMonacoEditorPlugin, loader } from '@guolao/vue-monaco-editor'
import * as monaco from 'monaco-editor'
import App from './App.vue'
import '@assets/css/styles.css'

import editorWorker from 'monaco-editor/esm/vs/editor/editor.worker?worker'
import jsonWorker from 'monaco-editor/esm/vs/language/json/json.worker?worker'
import cssWorker from 'monaco-editor/esm/vs/language/css/css.worker?worker'
import htmlWorker from 'monaco-editor/esm/vs/language/html/html.worker?worker'
import tsWorker from 'monaco-editor/esm/vs/language/typescript/ts.worker?worker'

self.MonacoEnvironment = {
  getWorker(_, label) {
    if (label === 'json') {
      return new jsonWorker()
    }
    if (label === 'css' || label === 'scss' || label === 'less') {
      return new cssWorker()
    }
    if (label === 'html' || label === 'handlebars' || label === 'razor') {
      return new htmlWorker()
    }
    if (label === 'typescript' || label === 'javascript') {
      return new tsWorker()
    }
    return new editorWorker()
  },
}

loader.config({ monaco })
const app = createApp(App)
app.use(VueMonacoEditorPlugin)
app.mount('#app')

`
