### ISSUE TITLE
I use vue@3.3.9  but i don't  install by npm. 

### ISSUE THREAD

**Issue by Jacky-YC** [imguolao/monaco-vue#40]
Could not resolve dependency:
@guolao/vue-monaco-editor@"*" from the root project

Conflicting peer dependency: vue@3.3.9
node_modules/vue
  peer vue@">= 2.5 < 2.7" from @vue/composition-api@1.7.2
  node_modules/@vue/composition-api
    peerOptional @vue/composition-api@"^1.7.1" from @guolao/vue-monaco-editor@1.4.0
    node_modules/@guolao/vue-monaco-editor
      @guolao/vue-monaco-editor@"*" from the root project

Fix the upstream dependency conflict, or retry
this command with --force or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.

**Comment by imguolao** [comment]
What are your npm and node versions?

`@vue/composition-api` is set to optional [here](https://github.com/imguolao/monaco-vue/blob/afe8c9969f5b5dec7dd8a0be121280c62fc34e9a/packages/editor/package.json#L70-L73), but it didn't take effect when you installed it?
