### ISSUE TITLE
why not lien prop does not work

### ISSUE THREAD

**Issue by lenran659** [imguolao/monaco-vue#42]
<vue-monaco-editor
                  v-show="showEdit"
                  :line="item.line"
                  v-model:value="mainStore.$state.raw_data"
                  theme="vs-dark"
                  :options="MONACO_EDITOR_OPTIONS"
                  @mount="handleMount"
                  height="200px"
 />

**Comment by imguolao** [comment]
Bug fixed, try verson@1.4.1?
