### ISSUE TITLE
Update monaco-editor

### ISSUE THREAD

**Issue by GoldraK** [imguolao/monaco-vue#49]
The monaco-editor dependency is in version 0.45.0 and the package in 0.43.0.

Thanks.

**Comment by imguolao** [comment]
Can be configured to use version 0.45, versions in dependencies can be ignored:

```js
app.use(VueMonacoEditorPlugin, {
  paths: {
    // 0.45
    vs: 'https://cdn.jsdelivr.net/npm/monaco-editor@0.45.0/min/vs'
  },
})
```

**Comment by GoldraK** [comment]
Yes I tried this and work, but i refer to the npm peerDependencies
