### ISSUE TITLE
monaco-vue自身的滚动条到底部后外部的滚动条滚轮无法控制

### ISSUE THREAD

**Issue by joshua-geng3** [imguolao/monaco-vue#5]
![image](https://user-images.githubusercontent.com/50396622/176384411-112c4701-0df7-4308-b04e-15b8ee3c6932.png)

**Comment by imguolao** [comment]
能否提供一个最小实现？可以 fork 仓库修改 playground 下的代码来复现。

因为 monaco-editor 实现并维护自身的滚动条，所以在 dom 上只能控制自身滚动条，是无法控制外层滚动条的。

**Comment by imguolao** [comment]
如果你需要实现该功能，可以参考此 issue 

https://github.com/microsoft/monaco-editor/issues/2243
