### ISSUE TITLE
Missing functions inside useMonaco

### ISSUE THREAD

**Issue by prd-nhan-ho** [imguolao/monaco-vue#52]
![Screenshot 2024-04-11 at 14 54 40](https://github.com/imguolao/monaco-vue/assets/156631160/375bc4ea-b2c2-4461-886a-2455621b6405)

I console.log the editor property in `useMonaco` and some functions relating to model handling like `setModel`,... are not there. Any guess?

**Comment by imguolao** [comment]
You can read [documentation of monaco-editor](https://microsoft.github.io/monaco-editor/docs.html#interfaces/editor.IStandaloneCodeEditor.html#setModel)

The functions exist in the editor instance, not monaco instance.

```ts
editor.IStandaloneCodeEditor.setModel(model: ITextModel): void
```

**Comment by prd-nhan-ho** [comment]
![Screenshot 2024-04-11 at 15 32 34](https://github.com/imguolao/monaco-vue/assets/156631160/cefe2358-b163-4e6a-bddc-bcce2b496588)

Correct me if I'm wrong, but I think it is editor instance


> You can read [documentation of monaco-editor](https://microsoft.github.io/monaco-editor/docs.html#interfaces/editor.IStandaloneCodeEditor.html#setModel)
> 
> The functions exist in the editor instance, not monaco instance.
> 
> ```ts
> editor.IStandaloneCodeEditor.setModel(model: ITextModel): void
> ```

**Comment by imguolao** [comment]
Please read the documentation carefully, guy.

```ts
// The `useMonaco` funtion return a `monaco` instance.
const { monacoRef, unload } = useMonaco()

// Creating an `editor` instance, and the `setModel` function is here.
const editor = monacoRef.value.editor.create(...)
```

**Comment by prd-nhan-ho** [comment]
I just find out that the `setModel` function is inside `monacoInstance`, not in `editorInstance`. Here is the console.log result.

<img width="724" alt="Screenshot 2024-04-11 at 16 02 37" src="https://github.com/imguolao/monaco-vue/assets/156631160/ed043dd6-8ebd-4646-8f2c-883ae89a99be">


![Screenshot 2024-04-11 at 16 00 04](https://github.com/imguolao/monaco-vue/assets/156631160/0296d98f-1951-405e-bf45-f3d7076c9273)

**Comment by imguolao** [comment]
well, I'm glad you found it. Maybe we're having some communication problems.

You can try the following code that copy in a local html file and open it to get the log results.

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>UMD Example</title>
  <script src="https://unpkg.com/vue@3.3.7/dist/vue.global.js"></script>
  <script src="https://unpkg.com/vue-demi@0.14.6/lib/index.iife.js"></script>
  <script src="https://unpkg.com/@monaco-editor/loader@1.4.0/lib/umd/monaco-loader.js"></script>
  <script src="https://unpkg.com/@guolao/vue-monaco-editor@1.4.0/lib/umd/monaco-vue.js"></script>
  <style>
    html,
    body,
    #app {
      margin: 0;
      padding: 0;
      height: 100%;
    }
  </style>
</head>
<body>
  <div id="app">
    <!-- Will render here -->
  </div>
</body>

  <script>
    const { createApp, ref, shallowRef } = Vue
    const { VueMonacoEditor } = monaco_vue

    const app = createApp({
      components: {
        VueMonacoEditor,
      },

      template: `
        <vue-monaco-editor
          @mount="handleMount"
        />
      `,

      setup() {
        const handleMount = (editor, monaco) => {
          // ƒ setModel(te=null){...}
          console.log(editor.setModel)

          // undefined
          console.log(monaco.editor.setModel)
        }

        return {
          handleMount,
        }
      }
    })

    app.mount('#app')
</script>
</html>
```
