### ISSUE TITLE
页面绑定数据后,浏览器直接崩溃

### ISSUE THREAD

**Issue by fiveiiii** [imguolao/monaco-vue#58]
问题描述:
![image](https://github.com/imguolao/monaco-vue/assets/49238306/cc5ea155-e516-4be8-bbaa-5a4cbd8e2ba7)
这是页面代码
![image](https://github.com/imguolao/monaco-vue/assets/49238306/b4142206-10b6-436b-ae57-528d5d7eba9d)

**Comment by imguolao** [comment]
无法复现，能提供个最小例子或者 github repo 吗？
