### ISSUE TITLE
与ubuntu24.04不兼容

### ISSUE THREAD

**Issue by redisviewer** [imguolao/monaco-vue#59]
![无标题](https://github.com/imguolao/monaco-vue/assets/12822830/dfc2c18e-2f1e-4364-aeb3-506bec333af4)
![image](https://github.com/imguolao/monaco-vue/assets/12822830/33c37d8e-6608-467d-9630-c9bfe1d7c77d)

 
我本地独立添加不行....  一样load fail 
`yarn add monaco-editor@0.48.0 --dev`

试试看升级0.48？

**Comment by imguolao** [comment]
JsDelivr CDN 国内证书过期了，换个可用 CDN 或者[本地 import 使用](https://github.com/imguolao/monaco-vue?tab=readme-ov-file#npm-package)。

**Comment by redisviewer** [comment]
哇作者辛苦了。
可是我不是专业前端。没看明白，能详细说说吗？

**Comment by imguolao** [comment]
编辑器默认是从 JsDelivr CDN 加载的，前两天国内证书过期了，CDN 失效了，现在应该恢复了
