### ISSUE TITLE
右键菜单如何汉化？

### ISSUE THREAD

**Issue by Xiangzi529** [imguolao/monaco-vue#61]
右键菜单如何汉化？右键菜单如何汉化？右键菜单如何汉化？

**Comment by imguolao** [comment]
可以去 monaco-editor 的 issues 里看看，这里只是用 vue 简单封装了一下。
https://github.com/microsoft/monaco-editor/issues/1514#issuecomment-1097462214

**Comment by Xiangzi529** [comment]
好的 谢谢
