### ISSUE TITLE
Undo/Redo regression in v1.5.2

### ISSUE THREAD

**Issue by iamandrewluca** [imguolao/monaco-vue#67]
Hey there! Thanks a lot for the effort put into this library.

Recently I updated to `v1.5.2` and it seems Undo/Redo functionality is not working anymore.
If downgrading to `v1.5.1`, everything it seems to be fine.
I suspect this PR introduced the regression https://github.com/imguolao/monaco-vue/pull/66

**Demo Video:**

https://github.com/user-attachments/assets/78f5aaa1-144b-4ac6-bee4-96a6f77b3bc1

**Comment by imguolao** [comment]
Thank you for reporting this issue. I'll take some time over the weekend to fix it.
