### ISSUE TITLE
如何不加载太多的编程语言

### ISSUE THREAD

**Issue by aogg** [imguolao/monaco-vue#73]
<img width="326" alt="image" src="https://github.com/user-attachments/assets/305b5efe-03d2-44fe-9b2d-50f3ebf1d72d">

**Comment by imguolao** [comment]
[配置 loader 即可](https://github.com/imguolao/monaco-vue?tab=readme-ov-file#cdn)

```js
loader.config({
  paths: {
    vs: "...",
  },
  "vs/nls" : {
    ...
  },
})
```

**Comment by aogg** [comment]
真心看不懂，如何本地加载不走cdn，如何不加载mysql各种语言的格式，提高加载速度

下面这样也不对啊
```
loader.config({
  paths: {
    vs: 'https://cdn.jsdelivr.net/npm/monaco-editor@0.43.0/min/vs'
  },
  "vs/nls" : {
    availableLanguages: {
      "*": "de",
    },
  },
})
```

**Comment by imguolao** [comment]
> 真心看不懂，如何本地加载不走cdn，如何不加载mysql各种语言的格式，提高加载速度
> 
> 下面这样也不对啊
> 
> ```
> loader.config({
>   paths: {
>     vs: 'https://cdn.jsdelivr.net/npm/monaco-editor@0.43.0/min/vs'
>   },
>   "vs/nls" : {
>     availableLanguages: {
>       "*": "de",
>     },
>   },
> })
> ```

本地加载， loader 配置从 npm 包引入的 monaco 就行，文档都有写。
```
import * as monaco from "monaco-editor"
import { loader } from "@guolao/vue-monaco-editor"

// loaded monaco-editor from `node_modules`
loader.config({ monaco })
```

CDN 加载编辑器的话，语言文件是懒加载的，如果组件上不设置 language 的值，只会加载编辑器基础文件。

如果是你打包引入了其他语言文件，只跟你的 vite, webpack 这些打包设置有关，与封装的组件和 loader 无关。

另外，提 issue 想让人帮忙解决问题，尽量把环境，代码，报错，执行结果都描述下，放张截图没人看得懂你想表达什么。
