### ISSUE TITLE
只有在第一个字才会触发 provider 

### ISSUE THREAD

**Issue by bestK** [imguolao/monaco-vue#74]
![GIF 2024-8-30 18-26-46](https://github.com/user-attachments/assets/43f047f9-5215-4bb5-8221-4dc4ad2c0b82)

```
    // 注册代码片段
    monaco.languages.registerCompletionItemProvider('aviatorscript', {
        provideCompletionItems: function () {
            return { suggestions: suggestions };
        },
    });
```

**Comment by imguolao** [comment]
你的提示写得太简单了，可以参考下其他开源的写法，比如 [nginx-editor](https://github.com/jaywcjlove/nginx-editor/blob/c0a4b62ad0ad401f703e8ac3b711d9da9e700cec/src/index.tsx#L7-L60)
