### ISSUE TITLE
Use in Tabs

### ISSUE THREAD

**Issue by dioubernardo** [imguolao/monaco-vue#78]
I used the code from the "Usage > Editor" section of Readme.md and placed it in a component (CodeEditor.vue).

In a view I used the component inside a Tabs

```
<Tabs default-value="code" class="h-full">
	<TabsList>
	  <TabsTrigger value="code">
		code.R
	  </TabsTrigger>
	  <TabsTrigger value="data">
		data.csv
	  </TabsTrigger>
	</TabsList>
	<TabsContent value="code" class="h-full">
	  <CodeEditor />
	</TabsContent>
	<TabsContent value="data" class="h-full">
	  dados
	</TabsContent>
</Tabs>
```
If I run run dev and open it in the browser, everything is working fine, but if I position the cursor or select text in the editor and change tabs, when I return to the editor the selection or cursor position is lost.

When reading the documentation I thought saveViewState would solve this.

**Comment by imguolao** [comment]
The `saveViewState` configuration is not globally saved, and the saved state will be destroyed along with the component when the `editor` component is unmounted. 

Therefore, switching different `model` by changing the `path` prop  while the component is not unmounted will save the state of the `model` being switched. Saving globally could be a memory leak problem, so I didn't do it. 

So, maybe the `editor` component is unmounted when you change tabs, and editor model states is lost at the moment. 

You can save the model state yourself:

```vue
<template>
  <vue-monaco-editor @mount="handleMount" />
</template>

<script lang="ts" setup>
import { shallowRef, onBeforeUnmount } from 'vue'

const editor = shallowRef()
const handleMount = editorInstance => {
  editor.value = editorInstance

  // get state and restore state by globally save
  const state = globalStroe.get(key)
  editor.value!.restoreViewState(state)
}

onBeforeUnmount(() => {
  const state = editor.value!.saveViewState()

  // globally save
  globalStroe.save(key, state)
})
</script>
```

Or if you have a better idea, pr welcome.

**Comment by dioubernardo** [comment]
Hello, thank you very much for the answer.

I ended up finding a solution in Vue, making it not unmount the component.

However, I had to stop using Tabs.

```
<script setup type="ts">
import CodeEditor from '@/components/CodeEditor.vue'
....
</script>
<template>
...
<Button @click="activeTab = 'code'" />
<div v-show="activeTab === 'code'" class="h-full">
  <KeepAlive>
    <component :is="CodeEditor"></component>
  </KeepAlive>
</div>
...
```

**Comment by imguolao** [comment]
I'm glad I could help you.
