### ISSUE TITLE
Vue 2 support?

### ISSUE THREAD

**Issue by jonalxh** [imguolao/monaco-vue#8]
Hi, I was trying to add this component to my Vue 2 project and it requires Vue 3. Are you planning to add Vue 2 support?

**Comment by imguolao** [comment]
sry, There are no plans to support vue2.

Because vue has 3 version (<=2.6, 2.7, 3.x)，ans [vue-demi](https://github.com/vueuse/vue-demi) doesn't completely eliminate the differences between them, so only vue3 is supported now.

**Comment by imguolao** [comment]
version `v1` suport vue 2&3 now #9
